FROM alpine:3.21

# Need to grab terraform binary

RUN apk add --no-cache curl git openssh unzip
RUN curl -sLf https://releases.hashicorp.com/terraform/1.10.5/terraform_1.10.5_linux_amd64.zip -o terraform_1.10.5_linux_amd64.zip && \
    unzip terraform_1.10.5_linux_amd64.zip -d /usr/bin && \
    chmod +x /usr/bin/terraform && \
    rm terraform_1.10.5_linux_amd64.zip

COPY terraform-executor /usr/bin/

RUN mkdir -p /root/module
WORKDIR /root/module

CMD ["terraform-executor"]
